name: add-discord-role

on:
  workflow_call:
    inputs:
      team_slug:
        required: true
        type: string
      discord_handle:
        required: true
        type: string
    secrets:
      PAT:
        required: true
      DISCORD_DEVBOT_TOKEN:
        required: true
      DISCORD_SOLANA_GUILD_ID:
        required: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: parse-info
        shell: bash
        id: info
        run: |
          set -e

          if [[ ! "${{ inputs.discord_handle }}" =~ ([^#]+)#([0-9]+)$ ]]; then
            echo "unexpected discord handle"
            exit 1
          fi

          username="${BASH_REMATCH[1]}"
          discriminator="${BASH_REMATCH[2]}"

          userid=$(
            curl -s -H "Authorization: Bot ${{ secrets.DISCORD_DEVBOT_TOKEN }}" \
              "https://discord.com/api/guilds/${{ secrets.DISCORD_SOLANA_GUILD_ID }}/members/search?limit=1000&query=$username" | \
              jq --raw-output --arg discriminator "$discriminator" '.[] | select(.user.discriminator == $discriminator) | .user.id'
          )
          if [[ $userid = "null" ]]; then
            echo "failed to get user id"
            exit 1
          fi

          echo "userid=$userid" >> $GITHUB_OUTPUT

          case ${{ inputs.team_slug }} in
          "monorepo-triage")
            echo "new_role_name=Monorepo-Triage" >> $GITHUB_OUTPUT
            ;;
          "monorepo-write")
            echo "new_role_name=Monorepo-Write" >> $GITHUB_OUTPUT
            echo "old_role_name=Monorepo-Triage" >> $GITHUB_OUTPUT
            ;;
          "spl-triage")
            echo "new_role_name=SPL-Triage" >> $GITHUB_OUTPUT
            ;;
          "spl-write")
            echo "new_role_name=SPL-Write" >> $GITHUB_OUTPUT
            echo "old_role_name=SPL-Triage" >> $GITHUB_OUTPUT
            ;;
          *)
            echo "unexpected team slug: ${{ inputs.team_slug }}"
            exit 1
            ;;
          esac

      - name: add contributor role
        shell: bash
        run: |
          roleid=$(
            curl -s -H "Authorization: Bot ${{ secrets.DISCORD_DEVBOT_TOKEN }}" \
              "https://discord.com/api/guilds/${{ secrets.DISCORD_SOLANA_GUILD_ID }}/roles" | \
              jq -r '.[] | select(.name=="Contributor") | .id'
          )
          if [[ $roleid = "null" ]]; then
            echo "failed to get role id"
            exit 1
          fi

          curl -s \
            -X PUT \
            -H "Authorization: Bot ${{ secrets.DISCORD_DEVBOT_TOKEN }}" \
            -H "Content-Length: 0" \
            "https://discord.com/api/guilds/${{ secrets.DISCORD_SOLANA_GUILD_ID }}/members/${{ steps.info.outputs.userid }}/roles/$roleid"

      - name: add new role
        if: ${{ steps.info.outputs.new_role_name }}
        shell: bash
        run: |
          roleid=$(
            curl -s -H "Authorization: Bot ${{ secrets.DISCORD_DEVBOT_TOKEN }}" \
              "https://discord.com/api/guilds/${{ secrets.DISCORD_SOLANA_GUILD_ID }}/roles" | \
              jq -r '.[] | select(.name=="${{ steps.info.outputs.new_role_name }}") | .id'
          )
          if [[ $roleid = "null" ]]; then
            echo "failed to get role id"
            exit 1
          fi

          curl -s \
            -X PUT \
            -H "Authorization: Bot ${{ secrets.DISCORD_DEVBOT_TOKEN }}" \
            -H "Content-Length: 0" \
            "https://discord.com/api/guilds/${{ secrets.DISCORD_SOLANA_GUILD_ID }}/members/${{ steps.info.outputs.userid }}/roles/$roleid"

      - name: remove old role
        if: ${{ steps.info.outputs.old_role_name }}
        shell: bash
        run: |
          roleid=$(
            curl -s -H "Authorization: Bot ${{ secrets.DISCORD_DEVBOT_TOKEN }}" \
              "https://discord.com/api/guilds/${{ secrets.DISCORD_SOLANA_GUILD_ID }}/roles" | \
              jq -r '.[] | select(.name=="${{ steps.info.outputs.old_role_name }}") | .id'
          )
          if [[ $roleid = "null" ]]; then
            echo "failed to get role id"
            exit 1
          fi

          curl -s \
            -X DELETE \
            -H "Authorization: Bot ${{ secrets.DISCORD_DEVBOT_TOKEN }}" \
            -H "Content-Length: 0" \
            "https://discord.com/api/guilds/${{ secrets.DISCORD_SOLANA_GUILD_ID }}/members/${{ steps.info.outputs.userid }}/roles/$roleid"

      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ["discord"]
            })
